# Generated by Django 3.2.4 on 2021-06-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20210629_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='chest',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='hem',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='length',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rise',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shoulder',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sleeve',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='waist',
        ),
    ]
