# Generated by Django 3.2.3 on 2021-06-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='store',
            old_name='title',
            new_name='Name',
        ),
    ]
