# Generated by Django 3.2.3 on 2021-06-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20210629_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='blog_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.store'),
        ),
    ]
