# Generated by Django 3.2.3 on 2021-06-29 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_model_blog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mnumber', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('type', models.CharField(max_length=300)),
                ('blog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.store')),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
