# Generated by Django 3.2.3 on 2021-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_auto_20210629_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingmodel',
            name='Mname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
