# Generated by Django 3.2.4 on 2021-06-29 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('length', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('chest', models.IntegerField()),
                ('sleeve', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('crotch', models.IntegerField()),
                ('hem', models.IntegerField()),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.item')),
            ],
        ),
    ]
