# Generated by Django 3.2.4 on 2021-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210629_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='shop_url',
            field=models.URLField(null=True),
        ),
    ]
